"""
Ad Platform MVP - Models Module

Pydantic models for the application.
"""

from app.models.account import (
    Platform,
    AccountStatus,
    SyncStatus,
    OAuthInitiateRequest,
    OAuthInitiateResponse,
    OAuthCallbackRequest,
    OAuthCallbackResponse,
    ConnectedAccountResponse,
    ConnectedAccountList,
    ConnectedAccountDetail,
    SyncJobResponse,
    SyncTriggerRequest,
    SyncTriggerResponse,
)
from app.models.metrics import (
    DateRange,
    DateRangePreset,
    BaseMetrics,
    DailyMetrics,
    MetricChange,
    MetricsSummary,
    MetricsByDate,
    MetricsTrend,
    CampaignMetrics,
    CampaignMetricsList,
    PlatformMetrics,
    MetricsByPlatform,
)
from app.models.insight import (
    InsightType,
    InsightPriority,
    ActionStatus,
    InsightResponse,
    InsightList,
    InsightReadRequest,
    InsightDismissRequest,
    ActionResponse,
    ActionList,
    ActionExecuteRequest,
    ActionExecuteResponse,
    ActionDismissRequest,
    DailyDigestResponse,
    DigestList,
)
from app.models.common import (
    SuccessResponse,
    ErrorResponse,
    ErrorDetail,
    PaginationMeta,
    PaginatedResponse,
    HealthResponse,
    ErrorCodes,
)

__all__ = [
    # Account
    "Platform",
    "AccountStatus", 
    "SyncStatus",
    "OAuthInitiateRequest",
    "OAuthInitiateResponse",
    "OAuthCallbackRequest",
    "OAuthCallbackResponse",
    "ConnectedAccountResponse",
    "ConnectedAccountList",
    "ConnectedAccountDetail",
    "SyncJobResponse",
    "SyncTriggerRequest",
    "SyncTriggerResponse",
    # Metrics
    "DateRange",
    "DateRangePreset",
    "BaseMetrics",
    "DailyMetrics",
    "MetricChange",
    "MetricsSummary",
    "MetricsByDate",
    "MetricsTrend",
    "CampaignMetrics",
    "CampaignMetricsList",
    "PlatformMetrics",
    "MetricsByPlatform",
    # Insights
    "InsightType",
    "InsightPriority",
    "ActionStatus",
    "InsightResponse",
    "InsightList",
    "InsightReadRequest",
    "InsightDismissRequest",
    "ActionResponse",
    "ActionList",
    "ActionExecuteRequest",
    "ActionExecuteResponse",
    "ActionDismissRequest",
    "DailyDigestResponse",
    "DigestList",
    # Common
    "SuccessResponse",
    "ErrorResponse",
    "ErrorDetail",
    "PaginationMeta",
    "PaginatedResponse",
    "HealthResponse",
    "ErrorCodes",
]
